name: Publish to PyPI
on: [release]
jobs:
  Publish-to-PyPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        # - uses: BSFishy/pip-action@v1
        # with:
        #  packages: twine
      - uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          build: true
          skip_existing: true
